<a href="https://colab.research.google.com/github/jaispankaj/data_science/blob/master/LinearRegressionExample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

X=np.random.randint(1,20,size=(10,10))
Y=np.random.randint(1,10,size=(10,1))

X=np.matrix(X)
Y=np.matrix(Y)
#by grdient descent W=(((X.T)X)^-1)(X.T)Y
W = np.matmul(np.linalg.inv(np.matmul(X.T,X)),np.matmul(X.T,Y))

print(X)
print(Y)
print(W)

[[15  9  8 11 14 13 15 18  1 17]
 [16  5 19 12  1 10  1 15  4 10]
 [ 4 15 17 17  5 18  1  2 16  6]
 [15  5  2 13  3 15 10  6 17  9]
 [12  2 11 10 16 18 13 10  1  6]
 [10 19 10  1  3  1 17  9 16 16]
 [ 5 16  7  5  8 18 11 12  5  1]
 [12  9  9 10 11 17  6 19  6  3]
 [14 14 15 11 14 11  4 15 19  7]
 [ 5 15 18  2 16 10  7  1  5  4]]
[[9]
 [8]
 [4]
 [6]
 [1]
 [1]
 [3]
 [8]
 [9]
 [4]]
[[ 0.34803877]
 [ 0.06956951]
 [-0.41911776]
 [-1.35618833]
 [ 0.24330833]
 [ 1.17186612]
 [-1.50217748]
 [ 0.09939675]
 [ 0.15555781]
 [ 1.37480549]]
