<a href="https://colab.research.google.com/github/jaispankaj/data_science/blob/master/TesorflowExample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import numpy as np

In [0]:
a=tf.Variable(0.0,tf.float32)
b=tf.Variable(1.0,tf.float32)
c=tf.Variable(1.0,tf.float32)
assign1=tf.assign(c,a+b)
assign2=tf.assign(a,b)
assign3=tf.assign(b,c)
with tf.Session() as sess:
  sess.run(tf.initialize_all_variables())
  print(sess.run(a))
  print(sess.run(b))
  for i in range(10):
    sess.run(assign1)
    sess.run(assign2)
    sess.run(assign3)
    print(sess.run(c))

Instructions for updating:
Use `tf.global_variables_initializer` instead.
0.0
1.0
1.0
2.0
3.0
5.0
8.0
13.0
21.0
34.0
55.0
89.0


In [0]:
n_samples=1000
n_dims=100
X_data=np.random.randn(n_samples,n_dims)
TW=np.random.randn(n_dims,1)
Y_data=np.matmul(X_data,TW)+np.random.randn(n_samples,1)

In [0]:
B=100
X=tf.placeholder(tf.float32,shape=(B,n_dims))
Y=tf.placeholder(tf.float32,shape=(B,1))
W=tf.Variable(np.random.randn(n_dims,1),dtype=tf.float32)

In [0]:
Y_hat=tf.matmul(X,W)
Error=tf.reduce_sum((Y_hat-Y)**2/n_samples)
opt=tf.train.AdamOptimizer()
opt_operation=opt.minimize(Error)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [0]:
with tf.Session() as sess:
  sess.run(tf.initialize_all_variables())
  for i in range(10):
    indices=np.random.choice(n_samples,B)
    X_batch=X_data[indices]
    Y_batch=Y_data[indices]
    e,error=sess.run([opt_operation,Error],feed_dict={X:X_batch,Y:Y_batch})
    print(error)

19.876831
17.249851
19.967695
19.900846
17.619698
25.94729
20.757338
18.363409
25.57778
23.39666


In [0]:
import numpy as np
from sklearn.cluster import KMeans
A=np.array([[0,1,0,1],[1,0,1,1],[0,1,0,0],[1,1,0,0]])
D=np.diag(A.sum(axis=1))
print(A)
print(D)
L=D-A 
vals,vecs=np.linalg.eig(L)
print(vals)
print(vecs)
vecs=vecs[:,np.argsort(vals)]
vals=vals[np.argsort(vals)]
print(vals)
print(vecs)
kmeans = KMeans(n_clusters=2)
kmeans.fit(vecs[:,1:2])
colors = kmeans.labels_
print("Clusters:", colors)


[[0 1 0 1]
 [1 0 1 1]
 [0 1 0 0]
 [1 1 0 0]]
[[2 0 0 0]
 [0 3 0 0]
 [0 0 1 0]
 [0 0 0 2]]
[ 4.00000000e+00  3.00000000e+00 -7.16704478e-17  1.00000000e+00]
[[-2.88675135e-01  7.07106781e-01  5.00000000e-01  4.08248290e-01]
 [ 8.66025404e-01  1.29398811e-15  5.00000000e-01  1.08555382e-16]
 [-2.88675135e-01 -2.32414411e-16  5.00000000e-01 -8.16496581e-01]
 [-2.88675135e-01 -7.07106781e-01  5.00000000e-01  4.08248290e-01]]
[-7.16704478e-17  1.00000000e+00  3.00000000e+00  4.00000000e+00]
[[ 5.00000000e-01  4.08248290e-01  7.07106781e-01 -2.88675135e-01]
 [ 5.00000000e-01  1.08555382e-16  1.29398811e-15  8.66025404e-01]
 [ 5.00000000e-01 -8.16496581e-01 -2.32414411e-16 -2.88675135e-01]
 [ 5.00000000e-01  4.08248290e-01 -7.07106781e-01 -2.88675135e-01]]
Clusters: [1 1 0 1]


In [0]:
import spacy

nlp = spacy.load('de_core_news_sm', disable=['parser', 'tagger', 'ner'])
tokenized = nlp.tokenizer.pipe(instructions.values)
tokenized = [t.text for doc in tokenized for t in doc]

OSError: ignored